apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: small-fargate
  region: eu-central-1

managedNodeGroups:
  - name: ng1
    instanceType: t3.small
    minSize: 0
    maxSize: 4
    desiredCapacity: 0

fargateProfiles:
  - name: fp
    selectors:
      - namespace: fargate-ns
        labels:
          run-on: fargate
